### ISSUE TITLE
Synchronous resolve?

### ISSUE THREAD

**Issue by srinivas-os** [krakenjs/shortstop#21]
I'm trying to use shortstop with the [config](https://github.com/lorenwest/node-config) module. I have a default.js file in my config folder where I create and export my configuration object by require()-ing a bunch of JSON files. The JSON values can contain shortstop directives. So before exporting the final configuration object for use by the node-config module, I would like to apply shortstop resolution to it.

I am not able to do this currently because shortstop.resolve is an async method and the module.exports will not wait for it to complete. So is there a Sync variation of the resolve method?

Note: I've already looked into the confit module, but I cannot use it due to my specific requirements.

**Comment by tlivings** [comment]
If using `confit` is not an option, no, due to the potential for a protocol to require asynchronous resolution, you can not resolve synchronously as required by the `config` module.
