### ISSUE TITLE
NPM High vulnerability on async dependency

### ISSUE THREAD

**Issue by alanperezg-iweb** [krakenjs/shortstop#28]
## Detailed Description
npm audit report reported a High vulnerability on the async dependency used in the shortstop dependency
<img width="566" alt="Screen Shot 2022-05-05 at 12 23 02" src="https://user-images.githubusercontent.com/98714566/166979038-aaa1cc17-c447-4b3f-9f40-5fef8fb3c038.png">

## Possible Implementation
For versions 0.x.x, 1.x.x and 2.x.x use an async version >= 2.6.4 for 3.x.x versions use >= 3.2.2
More details can be found here: https://github.com/advisories/GHSA-fwr7-v2mv-hh25

## Environment Details
* Version used: 1.0.3
* Environment versions:  Node v12.19.0, npm v6.14.13
* Operating System and version: OSX 10.15.7 (Catalina)

**Comment by tasdflkjweio** [comment]
Is this project still maintained?

**Comment by grawk** [comment]
Taking a look at this. Thank you.

**Comment by grawk** [comment]
Resolved by `+ shortstop@1.0.2`
